<a href="https://colab.research.google.com/github/anaperez10/AnaliticaIII-Salud/blob/main/Base_concatenada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


EJERCICIO PRÁCTICO - ANALÍTICA EN SALUD: CANTIDAD DE CIRUGÍAS

Generacion de base de datos post pandemia a trabajar.

In [84]:
#Conexión con colab
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [85]:
# Leer cada una de las bases de datos.
cx = pd.read_csv('/content/drive/MyDrive/Curso Analitica 3/cxpost.csv')
cronicos = pd.read_csv('/content/drive/MyDrive/Curso Analitica 3/cronicospost.csv')
usuarios = pd.read_csv('/content/drive/MyDrive/Curso Analitica 3/usuariospost.csv')

In [86]:
cx.head(5)

,Unnamed: 0,YEAR,MES,CODIGO SERVICIO HABILITACION,SERVICIO HABILITACION,TIPO IDENTIFICACION,NRODOC,FECHA NACIMIENTO,REGIMEN,CODIGO EPS,...,COD DIAGNOSTICO POSTQUIRURGICO,DIAGNOSTICO POSTQUIRURGICO,TIPO DE HERIDA,TIPO AISLAMIENTO,COMPLICACIONES,CATEGORIA COMPLICACION,ESPECIALIDAD,SEDE,IDCX,ADMISION
0,854,2021,ENERO,207.0,cirugia ortopedica,CC,308384,1971-02-10,subsidiado,1415.0,...,T818,OTRAS COMPLICACIONES DE PROCEDIMIENTOS NO CLAS...,contaminada,NaN,False,3.0,ortopedia,LEON XIII,109718.0,5466001
1,855,2021,ENERO,215.0,cirugia urologica,CC,308384,1971-02-10,subsidiado,1415.0,...,N359,ESTRECHEZ URETRAL NO ESPECIFICADA,limpia contaminada,Protector;,False,2.0,urologia,LEON XIII,109856.0,5466001
2,856,2021,ENERO,207.0,cirugia ortopedica,CC,308384,1971-02-10,subsidiado,1415.0,...,M869,OSTEOMIELITIS NO ESPECIFICADA,contaminada,Protector;,False,3.0,ortopedia,LEON XIII,110056.0,5466001
3,857,2021,ENERO,207.0,cirugia ortopedica,CC,308384,1971-02-10,subsidiado,1415.0,...,M866,OTRAS OSTEOMIELITIS CRONICAS,sucia,Protector;,False,2.0,ortopedia,LEON XIII,110349.0,5466001
4,858,2021,ENERO,207.0,cirugia ortopedica,CC,308384,1971-02-10,subsidiado,1415.0,...,M864,OSTEOMIELITIS CRONICA CON DRENAJE DEL SENO,contaminada,Protector;,False,2.0,ortopedia,LEON XIII,110480.0,5466001

Mas depuracion de la base de datos de cirugia. elementos post cirugia se eliminan

In [87]:
cx.columns.values

array(['Unnamed: 0', 'YEAR', 'MES', 'CODIGO SERVICIO HABILITACION',
       'SERVICIO HABILITACION', 'TIPO IDENTIFICACION', 'NRODOC',
       'FECHA NACIMIENTO', 'REGIMEN', 'CODIGO EPS',
       'DESCRIPCION EPS VALIDADA', 'FECHA ORDEN', 'ORIGEN ORDEN',
       'ORIGEN ADMSION', 'QUIROFANO', 'TIPO PROCEDIMIENTO',
       'FECHA PREANESTESIA', 'ASA', 'FECHA CIRUGIA', 'TIPO DE ANESTESIA',
       'FECHA RECUPERACION CX', 'VIA', 'COD CUPS',
       'NOMBRE DE PROCEDIMIENTO', 'PROCEDIMIENTO 0256',
       'COD DIAGNOSTICO PREQUIRURGICO', 'DESCRIPCION PREQUIRURGICO',
       'CIE 10 TERCER CARACTER', 'DESCRIPCION TERCER CARACTER',
       'CAPITULO CIE10', 'NOMBRE CAPITULO',
       'COD DIAGNOSTICO POSTQUIRURGICO', 'DIAGNOSTICO POSTQUIRURGICO',
       'TIPO DE HERIDA', 'TIPO AISLAMIENTO', 'COMPLICACIONES',
       'CATEGORIA COMPLICACION', 'ESPECIALIDAD', 'SEDE', 'IDCX',
       'ADMISION'], dtype=object)

In [88]:
cx = cx.drop(['Unnamed: 0','SERVICIO HABILITACION','TIPO IDENTIFICACION','DESCRIPCION EPS VALIDADA','ASA','DESCRIPCION PREQUIRURGICO','NOMBRE DE PROCEDIMIENTO','DESCRIPCION PREQUIRURGICO','CIE 10 TERCER CARACTER','DESCRIPCION TERCER CARACTER','CAPITULO CIE10','NOMBRE CAPITULO','COD DIAGNOSTICO POSTQUIRURGICO','DIAGNOSTICO POSTQUIRURGICO','TIPO DE HERIDA', 'TIPO AISLAMIENTO', 'COMPLICACIONES',
       'CATEGORIA COMPLICACION',], axis=1)
cx

,YEAR,MES,CODIGO SERVICIO HABILITACION,NRODOC,FECHA NACIMIENTO,REGIMEN,CODIGO EPS,FECHA ORDEN,ORIGEN ORDEN,ORIGEN ADMSION,...,TIPO DE ANESTESIA,FECHA RECUPERACION CX,VIA,COD CUPS,PROCEDIMIENTO 0256,COD DIAGNOSTICO PREQUIRURGICO,ESPECIALIDAD,SEDE,IDCX,ADMISION
0,2021,ENERO,207.0,308384,1971-02-10,subsidiado,1415.0,2020-12-31,urgencias adultos,hospitalizacion,...,ninguna,2021-01-02,unica via,862006,862006.0,T818,ortopedia,LEON XIII,109718.0,5466001
1,2021,ENERO,215.0,308384,1971-02-10,subsidiado,1415.0,2021-01-04,ambulatorio,hospitalizacion,...,NaN,2021-01-06,unica via,580050,580050.0,N359,urologia,LEON XIII,109856.0,5466001
2,2021,ENERO,207.0,308384,1971-02-10,subsidiado,1415.0,2021-01-09,ambulatorio,hospitalizacion,...,general,2021-01-13,multiple procedimiento mismo especialista igua...,770501,770501.0,M869,ortopedia,LEON XIII,110056.0,5466001
3,2021,ENERO,207.0,308384,1971-02-10,subsidiado,1415.0,2021-01-19,ambulatorio,hospitalizacion,...,local asistida,2021-01-21,multiple procedimiento mismo especialista igua...,770501,770501.0,M866,ortopedia,LEON XIII,110349.0,5466001
4,2021,ENERO,207.0,308384,1971-02-10,subsidiado,1415.0,2021-01-25,ambulatorio,hospitalizacion,...,NaN,2021-01-26,unica via,770501,770501.0,M864,ortopedia,LEON XIII,110480.0,5466001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1082,2022,MAYO,207.0,312770,1950-05-07,contributivo,1791.0,2022-05-27,ambulatorio,cirugia,...,general,2022-05-28,unica via,44304,44304.0,G560,ortopedia,PRADO,132416.0,6121284
1083,2022,MAYO,207.0,313334,1947-03-28,contributivo,1791.0,2022-05-28,ambulatorio,cirugia,...,general,2022-05-28,unica via,44304,44304.0,G560,ortopedia,PRADO,132427.0,6121928
1084,2022,JUNIO,213.0,307306,1936-10-15,contributivo,3289.0,2022-06-02,ambulatorio,cirugia,...,local asistida,2022-06-03,multiple procedimiento mismo especialista dife...,867203,867203.0,C443,cirugia plastica,PRADO,132700.0,6129844
1085,2022,JUNIO,203.0,307270,1956-12-22,contributivo,1791.0,2022-06-06,ambulatorio,cirugia,...,general,2022-06-07,unica via,535204,535204.0,K439,cirugia general,PRADO,132904.0,6136389
1086,2022,JUNIO,NaN,313523,1979-05-11,contributivo,1791.0,2022-06-15,ambulatorio,cirugia,...,general,2022-06-16,unica via,862701,862701.0,L600,dermatologia,PRADO,133370.0,6150985

In [89]:
cronicos.head(5)

,Unnamed: 0,YEAR,MES,Fecha diligenciamiento,Hora,Atención,Ingreso,Tipo,NRODOC,Peso,...,VO2 - Máxima Cantidad de Oxígeno,Índice de Fragilidad Groningen,Calificación (Índice de Fragilidad),Tiempo en Segundos (Apoyo Monopodal),Calificación (Apoyo Monopodal),Tiempo en Segundos (Recorrer 5 metros),Velocidad (m/s),Calificación Velocidad,Requiere cita de morbilidad,Ambito según el médico
0,12827,2021,ENERO,2021-01-01,12:13:45 a.m.,5465666,3668418,CC,310176,56.0,...,13.8855,9.0,Frágil,9,Malo - Fragil,6,0.83,Deficiente,Si,Domiciliario
1,12828,2021,ENERO,2021-01-01,8:01:46 p.m.,5459773,3670506,CC,312214,39.0,...,35.3671,8.0,Frágil,10,Aceptable,6,0.83,Deficiente,Si,Domiciliario
2,12829,2021,ENERO,2021-01-03,8:41:16 p.m.,5456426,3670496,CC,311627,88.0,...,12.5212,9.0,Frágil,0,Malo - Fragil,0,0.00,Malo - Frágil,No,Domiciliario
3,12831,2021,ENERO,2021-01-04,8:33:34 a.m.,4306788,3669378,CC,307827,65.2,...,17.2497,10.0,Frágil,0,Malo - Fragil,9,0.56,Malo - Frágil,Si,Domiciliario
4,12833,2021,ENERO,2021-01-04,8:40:58 a.m.,5325410,3670145,CC,312431,55.0,...,13.0032,4.0,Normal,6,Malo - Fragil,8,0.63,Deficiente,No,Domiciliario

In [90]:
cronicos.columns.values

array(['Unnamed: 0', 'YEAR', 'MES', 'Fecha diligenciamiento', 'Hora',
       'Atención', 'Ingreso', 'Tipo', 'NRODOC', 'Peso', 'Talla', 'IMC',
       'Clasificación IMC', 'Saturación de Oxígeno (%)',
       'Perímetro Muslo', 'Perímetro Cintura', 'Pliegue Triceps',
       'Pliegue Abdomen', 'Pliegue Muslo', 'Sumatoria Pliegues',
       'Presión Arterial Sistólica', 'Presión Arterial Diastólica',
       'Frecuencia Cardíaca en reposo',
       'Auto-calificacion Nivel de Ejercicio', 'Constantes',
       'METS -Índice Metabólico', 'VO2 - Máxima Cantidad de Oxígeno',
       'Índice de Fragilidad Groningen',
       'Calificación (Índice de Fragilidad)',
       'Tiempo en Segundos (Apoyo Monopodal)',
       'Calificación (Apoyo Monopodal)',
       'Tiempo en Segundos (Recorrer 5 metros)', 'Velocidad (m/s)',
       'Calificación Velocidad', 'Requiere cita de morbilidad',
       'Ambito según el médico'], dtype=object)

In [91]:
cronicos = cronicos.drop(['Unnamed: 0','Tipo','Clasificación IMC','Calificación (Índice de Fragilidad)','Calificación (Apoyo Monopodal)','Calificación Velocidad'], axis=1)
cronicos

,YEAR,MES,Fecha diligenciamiento,Hora,Atención,Ingreso,NRODOC,Peso,Talla,IMC,...,Auto-calificacion Nivel de Ejercicio,Constantes,METS -Índice Metabólico,VO2 - Máxima Cantidad de Oxígeno,Índice de Fragilidad Groningen,Tiempo en Segundos (Apoyo Monopodal),Tiempo en Segundos (Recorrer 5 metros),Velocidad (m/s),Requiere cita de morbilidad,Ambito según el médico
0,2021,ENERO,2021-01-01,12:13:45 a.m.,5465666,3668418,310176,56.0,155.0,23.31,...,1,0.00,3.9673,13.8855,9.0,9,6,0.83,Si,Domiciliario
1,2021,ENERO,2021-01-01,8:01:46 p.m.,5459773,3670506,312214,39.0,156.0,16.03,...,1,0.00,10.1049,35.3671,8.0,10,6,0.83,Si,Domiciliario
2,2021,ENERO,2021-01-03,8:41:16 p.m.,5456426,3670496,311627,88.0,158.0,35.25,...,1,0.00,3.5775,12.5212,9.0,0,0,0.00,No,Domiciliario
3,2021,ENERO,2021-01-04,8:33:34 a.m.,4306788,3669378,307827,65.2,165.0,23.95,...,1,0.00,4.9285,17.2497,10.0,0,9,0.56,Si,Domiciliario
4,2021,ENERO,2021-01-04,8:40:58 a.m.,5325410,3670145,312431,55.0,150.0,24.44,...,1,0.00,3.7152,13.0032,4.0,6,8,0.63,No,Domiciliario
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25284,2022,MAYO,2022-05-31,10:55:31 p.m.,3419528,3630125,308916,65.0,165.0,23.88,...,1,0.00,4.3204,15.1214,8.0,0,9,0.56,No,Domiciliario
25285,2022,MAYO,2022-05-31,10:59:58 p.m.,5850632,4314997,306248,60.0,160.0,23.44,...,1,0.00,3.9052,13.6682,7.0,2,9,0.56,No,Domiciliario
25286,2022,MAYO,2022-05-31,11:13:57 p.m.,3413909,3630054,310546,48.0,160.0,18.75,...,1,0.00,4.3425,15.1988,9.0,0,0,0.00,No,Domiciliario
25287,2022,MAYO,2022-05-31,11:17:35 p.m.,5783823,4089709,309601,60.0,165.0,22.04,...,3,1.06,4.9332,17.2662,9.0,0,0,0.00,No,Domiciliario
25288,2022,MAYO,2022-05-31,11:25:39 p.m.,3991645,3434751,311850,75.0,164.0,27.89,...,1,0.00,3.5687,12.4904,8.0,1,6,0.83,No,Domiciliario

In [92]:
cronicos.columns= cronicos.columns.str.lower()
cx.columns= cx.columns.str.lower()

In [93]:
usuarios

,Unnamed: 0,mes,año,nrodoc,sexo,edad,municipio,ciclo_vital,quinquenio
0,101490,enero,2021,311028,m,69,sabaneta,vejez,65-69
1,101491,enero,2021,310961,m,75,bello,vejez,75-79
2,101492,enero,2021,311235,f,85,medellin,vejez,85-89
3,101493,enero,2021,307090,f,88,medellin,vejez,85-89
4,101494,enero,2021,310309,f,79,medellin,vejez,75-79
...,...,...,...,...,...,...,...,...,...
82416,183906,junio,2022,307482,f,81,medellin,vejez,80-84
82417,183907,junio,2022,313801,f,23,sin información,juventud,20-24
82418,183908,junio,2022,307738,f,78,medellin,vejez,75-79
82419,183909,junio,2022,311656,m,82,medellin,vejez,80-84
82420,183910,junio,2022,309230,m,65,envigado,vejez,65-69

In [94]:
usuarios = usuarios.drop(['Unnamed: 0','ciclo_vital','quinquenio'],axis=1)

In [95]:
#Base de datos con la informacion de todos los empleados
df = pd.merge(usuarios,cx, on = 'nrodoc',how = 'inner')
df1 = pd.merge(df,cronicos, on = 'nrodoc',how = 'inner')
df1

,mes_x,año,nrodoc,sexo,edad,municipio,year_x,mes_y,codigo servicio habilitacion,fecha nacimiento,...,auto-calificacion nivel de ejercicio,constantes,mets -índice metabólico,vo2 - máxima cantidad de oxígeno,índice de fragilidad groningen,tiempo en segundos (apoyo monopodal),tiempo en segundos (recorrer 5 metros),velocidad (m/s),requiere cita de morbilidad,ambito según el médico
0,enero,2021,309769,f,25,medellin,2021,OCTUBRE,209.0,1995-05-07,...,1,0.0,8.0890,28.3115,6.0,30,5,1.00,No,Ambulatorio
1,enero,2021,309769,f,25,medellin,2021,OCTUBRE,209.0,1995-05-07,...,1,0.0,7.1901,25.1654,2.0,0,6,0.83,No,Ambulatorio
2,enero,2021,309769,f,25,medellin,2021,OCTUBRE,209.0,1995-05-07,...,1,0.0,8.4475,29.5663,3.0,20,5,1.00,No,Ambulatorio
3,enero,2021,309769,f,25,medellin,2021,OCTUBRE,209.0,1995-05-07,...,1,0.0,8.8068,30.8238,2.0,10,5,1.00,No,Ambulatorio
4,febrero,2021,309769,f,25,medellin,2021,OCTUBRE,209.0,1995-05-07,...,1,0.0,8.0890,28.3115,6.0,30,5,1.00,No,Ambulatorio
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95822,mayo,2022,314187,f,79,medellin,2022,FEBRERO,214.0,1942-07-27,...,1,0.0,3.0236,10.5826,8.0,6,6,0.83,No,Domiciliario
95823,mayo,2022,314187,f,79,medellin,2022,FEBRERO,214.0,1942-07-27,...,1,0.0,3.0236,10.5826,8.0,6,6,0.83,Si,Domiciliario
95824,junio,2022,314187,f,79,medellin,2022,FEBRERO,214.0,1942-07-27,...,1,0.0,2.9036,10.1626,8.0,6,6,0.83,Si,Domiciliario
95825,junio,2022,314187,f,79,medellin,2022,FEBRERO,214.0,1942-07-27,...,1,0.0,3.0236,10.5826,8.0,6,6,0.83,No,Domiciliario
95826,junio,2022,314187,f,79,medellin,2022,FEBRERO,214.0,1942-07-27,...,1,0.0,3.0236,10.5826,8.0,6,6,0.83,Si,Domiciliario

In [96]:
df1=df1.drop_duplicates()

In [97]:
df1

,mes_x,año,nrodoc,sexo,edad,municipio,year_x,mes_y,codigo servicio habilitacion,fecha nacimiento,...,auto-calificacion nivel de ejercicio,constantes,mets -índice metabólico,vo2 - máxima cantidad de oxígeno,índice de fragilidad groningen,tiempo en segundos (apoyo monopodal),tiempo en segundos (recorrer 5 metros),velocidad (m/s),requiere cita de morbilidad,ambito según el médico
0,enero,2021,309769,f,25,medellin,2021,OCTUBRE,209.0,1995-05-07,...,1,0.0,8.0890,28.3115,6.0,30,5,1.00,No,Ambulatorio
1,enero,2021,309769,f,25,medellin,2021,OCTUBRE,209.0,1995-05-07,...,1,0.0,7.1901,25.1654,2.0,0,6,0.83,No,Ambulatorio
2,enero,2021,309769,f,25,medellin,2021,OCTUBRE,209.0,1995-05-07,...,1,0.0,8.4475,29.5663,3.0,20,5,1.00,No,Ambulatorio
3,enero,2021,309769,f,25,medellin,2021,OCTUBRE,209.0,1995-05-07,...,1,0.0,8.8068,30.8238,2.0,10,5,1.00,No,Ambulatorio
4,febrero,2021,309769,f,25,medellin,2021,OCTUBRE,209.0,1995-05-07,...,1,0.0,8.0890,28.3115,6.0,30,5,1.00,No,Ambulatorio
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95822,mayo,2022,314187,f,79,medellin,2022,FEBRERO,214.0,1942-07-27,...,1,0.0,3.0236,10.5826,8.0,6,6,0.83,No,Domiciliario
95823,mayo,2022,314187,f,79,medellin,2022,FEBRERO,214.0,1942-07-27,...,1,0.0,3.0236,10.5826,8.0,6,6,0.83,Si,Domiciliario
95824,junio,2022,314187,f,79,medellin,2022,FEBRERO,214.0,1942-07-27,...,1,0.0,2.9036,10.1626,8.0,6,6,0.83,Si,Domiciliario
95825,junio,2022,314187,f,79,medellin,2022,FEBRERO,214.0,1942-07-27,...,1,0.0,3.0236,10.5826,8.0,6,6,0.83,No,Domiciliario
95826,junio,2022,314187,f,79,medellin,2022,FEBRERO,214.0,1942-07-27,...,1,0.0,3.0236,10.5826,8.0,6,6,0.83,Si,Domiciliario

Warning: Total number of columns (58) exceeds max_columns (20) limiting to first (20) columns.
Warning: total number of rows (95814) exceeds max_rows (20000). Limiting to first (20000) rows.

In [98]:
df1.columns.values

array(['mes_x', 'año', 'nrodoc', 'sexo', 'edad', 'municipio', 'year_x',
       'mes_y', 'codigo servicio habilitacion', 'fecha nacimiento',
       'regimen', 'codigo eps', 'fecha orden', 'origen orden',
       'origen admsion', 'quirofano', 'tipo procedimiento',
       'fecha preanestesia', 'fecha cirugia', 'tipo de anestesia',
       'fecha recuperacion cx', 'via', 'cod cups', 'procedimiento 0256',
       'cod diagnostico prequirurgico', 'especialidad', 'sede', 'idcx',
       'admision', 'year_y', 'mes', 'fecha diligenciamiento', 'hora',
       'atención', 'ingreso', 'peso', 'talla', 'imc',
       'saturación de oxígeno (%)', 'perímetro muslo',
       'perímetro cintura', 'pliegue triceps', 'pliegue abdomen',
       'pliegue muslo', 'sumatoria pliegues',
       'presión arterial sistólica', 'presión arterial diastólica',
       'frecuencia cardíaca en reposo',
       'auto-calificacion nivel de ejercicio', 'constantes',
       'mets -índice metabólico', 'vo2 - máxima cantidad de oxígeno',
       'índice de fragilidad groningen',
       'tiempo en segundos (apoyo monopodal)',
       'tiempo en segundos (recorrer 5 metros)', 'velocidad (m/s)',
       'requiere cita de morbilidad', 'ambito según el médico'],
      dtype=object)

In [99]:
df1.isnull().sum()

mes_x                                         0
año                                           0
nrodoc                                        0
sexo                                          0
edad                                          0
municipio                                     0
year_x                                        0
mes_y                                         0
codigo servicio habilitacion                857
fecha nacimiento                              0
regimen                                       0
codigo eps                                    0
fecha orden                                   0
origen orden                                  0
origen admsion                                0
quirofano                                     0
tipo procedimiento                            0
fecha preanestesia                        10757
fecha cirugia                                 0
tipo de anestesia                         13502
fecha recuperacion cx                      4694
via                                           0
cod cups                                      0
procedimiento 0256                            0
cod diagnostico prequirurgico                 0
especialidad                                  0
sede                                          0
idcx                                          0
admision                                      0
year_y                                        0
mes                                           0
fecha diligenciamiento                        0
hora                                          0
atención                                      0
ingreso                                       0
peso                                          0
talla                                         0
imc                                           0
saturación de oxígeno (%)                     0
perímetro muslo                               0
perímetro cintura                             0
pliegue triceps                               0
pliegue abdomen                               0
pliegue muslo                                 0
sumatoria pliegues                            0
presión arterial sistólica                    0
presión arterial diastólica                   0
frecuencia cardíaca en reposo                 0
auto-calificacion nivel de ejercicio          0
constantes                                    0
mets -índice metabólico                       0
vo2 - máxima cantidad de oxígeno              0
índice de fragilidad groningen                0
tiempo en segundos (apoyo monopodal)          0
tiempo en segundos (recorrer 5 metros)        0
velocidad (m/s)                               0
requiere cita de morbilidad                   0
ambito según el médico                        0
dtype: int64

In [100]:
df1['tipo procedimiento'].value_counts()

quirurgico       93150
no quirurgico     2664
Name: tipo procedimiento, dtype: int64

In [101]:
df1['tipo de anestesia'].value_counts()

general           31881
raquidea          19430
local             16898
bloqueo            5523
local asistida     5352
ninguna            2510
epidural            718
Name: tipo de anestesia, dtype: int64

In [102]:
df1['codigo servicio habilitacion'].value_counts()

207.0    28662
217.0    19277
203.0    14150
213.0     7687
215.0     6434
214.0     6187
204.0     1878
235.0     1405
245.0     1402
209.0     1380
234.0     1338
206.0     1260
202.0     1167
218.0      906
210.0      905
201.0      396
205.0      339
241.0      184
Name: codigo servicio habilitacion, dtype: int64

In [103]:
df1['codigo servicio habilitacion']=df1['codigo servicio habilitacion'].fillna(217.0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [104]:
df1['tipo de anestesia']=df1['tipo de anestesia'].fillna('sin informe quirurgico')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [105]:
df2=df1[['nrodoc','tipo procedimiento','fecha cirugia']]
df2

       nrodoc tipo procedimiento fecha cirugia
0      309769         quirurgico    2021-10-13
1      309769         quirurgico    2021-10-13
2      309769         quirurgico    2021-10-13
3      309769         quirurgico    2021-10-13
4      309769         quirurgico    2021-10-13
...       ...                ...           ...
95822  314187         quirurgico    2022-02-09
95823  314187         quirurgico    2022-02-09
95824  314187         quirurgico    2022-02-09
95825  314187         quirurgico    2022-02-09
95826  314187         quirurgico    2022-02-09

[95814 rows x 3 columns]

In [106]:
df2.dtypes

nrodoc                 int64
tipo procedimiento    object
fecha cirugia         object
dtype: object

In [107]:
df2['fecha cirugia']=pd.to_datetime(df2['fecha cirugia'])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [108]:
df2['Year'] = df2['fecha cirugia'].dt.year
df2['Mes'] = df2['fecha cirugia'].dt.month

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [109]:
df2

       nrodoc tipo procedimiento fecha cirugia  Year  Mes
0      309769         quirurgico    2021-10-13  2021   10
1      309769         quirurgico    2021-10-13  2021   10
2      309769         quirurgico    2021-10-13  2021   10
3      309769         quirurgico    2021-10-13  2021   10
4      309769         quirurgico    2021-10-13  2021   10
...       ...                ...           ...   ...  ...
95822  314187         quirurgico    2022-02-09  2022    2
95823  314187         quirurgico    2022-02-09  2022    2
95824  314187         quirurgico    2022-02-09  2022    2
95825  314187         quirurgico    2022-02-09  2022    2
95826  314187         quirurgico    2022-02-09  2022    2

[95814 rows x 5 columns]

In [116]:
df2=df2.astype({'Mes': object})

In [112]:
import plotly.express as px

In [119]:
# crear dataset
base = df2.groupby(['Mes', 'Year'])[['nrodoc']].count().reset_index()
# MSSubClass: Tipo de edificio
# YrSold: Año en que se vende
# SalePrice: Precio de venta

# crear gráfica
fig = px.bar(base, x = 'Year', y='nrodoc', color = 'Mes', barmode = 'group', title= '<b>Precio de venta según el tipo de deficio por año<b>')

# agregar detalles a la gráfica
fig.update_layout(
    xaxis_title = 'Año',
    yaxis_title = 'Precio de venta',
    template = 'simple_white',
    title_x = 0.5)

fig.show()