<a href="https://colab.research.google.com/github/anaperez10/AnaliticaIII-Salud/blob/main/Copy_of_Base_concatenada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


EJERCICIO PRÁCTICO - ANALÍTICA EN SALUD: CANTIDAD DE CIRUGÍAS

Generacion de base de datos post pandemia a trabajar.

In [50]:
#Conexión con colab
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
from unicodedata import normalize

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [17]:
# Leer cada una de las bases de datos.
cx = pd.read_csv('/content/drive/MyDrive/Curso Analitica 3/cxpost.csv')
cronicos = pd.read_csv('/content/drive/MyDrive/Curso Analitica 3/cronicospost.csv')
usuarios = pd.read_csv('/content/drive/MyDrive/Curso Analitica 3/usuariospost.csv')

In [ ]:
cx.head(5)

,Unnamed: 0,YEAR,MES,CODIGO SERVICIO HABILITACION,SERVICIO HABILITACION,TIPO IDENTIFICACION,NRODOC,FECHA NACIMIENTO,REGIMEN,CODIGO EPS,...,COD DIAGNOSTICO POSTQUIRURGICO,DIAGNOSTICO POSTQUIRURGICO,TIPO DE HERIDA,TIPO AISLAMIENTO,COMPLICACIONES,CATEGORIA COMPLICACION,ESPECIALIDAD,SEDE,IDCX,ADMISION
0,854,2021,ENERO,207.0,cirugia ortopedica,CC,308384,1971-02-10,subsidiado,1415.0,...,T818,OTRAS COMPLICACIONES DE PROCEDIMIENTOS NO CLAS...,contaminada,NaN,False,3.0,ortopedia,LEON XIII,109718.0,5466001
1,855,2021,ENERO,215.0,cirugia urologica,CC,308384,1971-02-10,subsidiado,1415.0,...,N359,ESTRECHEZ URETRAL NO ESPECIFICADA,limpia contaminada,Protector;,False,2.0,urologia,LEON XIII,109856.0,5466001
2,856,2021,ENERO,207.0,cirugia ortopedica,CC,308384,1971-02-10,subsidiado,1415.0,...,M869,OSTEOMIELITIS NO ESPECIFICADA,contaminada,Protector;,False,3.0,ortopedia,LEON XIII,110056.0,5466001
3,857,2021,ENERO,207.0,cirugia ortopedica,CC,308384,1971-02-10,subsidiado,1415.0,...,M866,OTRAS OSTEOMIELITIS CRONICAS,sucia,Protector;,False,2.0,ortopedia,LEON XIII,110349.0,5466001
4,858,2021,ENERO,207.0,cirugia ortopedica,CC,308384,1971-02-10,subsidiado,1415.0,...,M864,OSTEOMIELITIS CRONICA CON DRENAJE DEL SENO,contaminada,Protector;,False,2.0,ortopedia,LEON XIII,110480.0,5466001

Mas depuracion de la base de datos de cirugia. elementos post cirugia se eliminan

In [18]:
cx.columns.values

array(['Unnamed: 0', 'YEAR', 'MES', 'CODIGO SERVICIO HABILITACION',
       'SERVICIO HABILITACION', 'TIPO IDENTIFICACION', 'NRODOC',
       'FECHA NACIMIENTO', 'REGIMEN', 'CODIGO EPS',
       'DESCRIPCION EPS VALIDADA', 'FECHA ORDEN', 'ORIGEN ORDEN',
       'ORIGEN ADMSION', 'QUIROFANO', 'TIPO PROCEDIMIENTO',
       'FECHA PREANESTESIA', 'ASA', 'FECHA CIRUGIA', 'TIPO DE ANESTESIA',
       'FECHA RECUPERACION CX', 'VIA', 'COD CUPS',
       'NOMBRE DE PROCEDIMIENTO', 'PROCEDIMIENTO 0256',
       'COD DIAGNOSTICO PREQUIRURGICO', 'DESCRIPCION PREQUIRURGICO',
       'CIE 10 TERCER CARACTER', 'DESCRIPCION TERCER CARACTER',
       'CAPITULO CIE10', 'NOMBRE CAPITULO',
       'COD DIAGNOSTICO POSTQUIRURGICO', 'DIAGNOSTICO POSTQUIRURGICO',
       'TIPO DE HERIDA', 'TIPO AISLAMIENTO', 'COMPLICACIONES',
       'CATEGORIA COMPLICACION', 'ESPECIALIDAD', 'SEDE', 'IDCX',
       'ADMISION'], dtype=object)

In [19]:
cx = cx.drop(['SERVICIO HABILITACION','TIPO IDENTIFICACION','DESCRIPCION EPS VALIDADA','ASA','DESCRIPCION PREQUIRURGICO','NOMBRE DE PROCEDIMIENTO','DESCRIPCION PREQUIRURGICO','CIE 10 TERCER CARACTER','DESCRIPCION TERCER CARACTER','CAPITULO CIE10','NOMBRE CAPITULO','COD DIAGNOSTICO POSTQUIRURGICO','DIAGNOSTICO POSTQUIRURGICO','TIPO DE HERIDA', 'TIPO AISLAMIENTO', 'COMPLICACIONES',
       'CATEGORIA COMPLICACION',], axis=1)
cx

,Unnamed: 0,YEAR,MES,CODIGO SERVICIO HABILITACION,NRODOC,FECHA NACIMIENTO,REGIMEN,CODIGO EPS,FECHA ORDEN,ORIGEN ORDEN,...,TIPO DE ANESTESIA,FECHA RECUPERACION CX,VIA,COD CUPS,PROCEDIMIENTO 0256,COD DIAGNOSTICO PREQUIRURGICO,ESPECIALIDAD,SEDE,IDCX,ADMISION
0,854,2021,ENERO,207.0,308384,1971-02-10,subsidiado,1415.0,1971-02-10,urgencias adultos,...,ninguna,1971-02-10,unica via,862006,862006.0,T818,ortopedia,LEON XIII,109718.0,5466001
1,855,2021,ENERO,215.0,308384,1971-02-10,subsidiado,1415.0,1971-02-10,ambulatorio,...,NaN,1971-02-10,unica via,580050,580050.0,N359,urologia,LEON XIII,109856.0,5466001
2,856,2021,ENERO,207.0,308384,1971-02-10,subsidiado,1415.0,1971-02-10,ambulatorio,...,general,1971-02-10,multiple procedimiento mismo especialista igua...,770501,770501.0,M869,ortopedia,LEON XIII,110056.0,5466001
3,857,2021,ENERO,207.0,308384,1971-02-10,subsidiado,1415.0,1971-02-10,ambulatorio,...,local asistida,1971-02-10,multiple procedimiento mismo especialista igua...,770501,770501.0,M866,ortopedia,LEON XIII,110349.0,5466001
4,858,2021,ENERO,207.0,308384,1971-02-10,subsidiado,1415.0,1971-02-10,ambulatorio,...,NaN,1971-02-10,unica via,770501,770501.0,M864,ortopedia,LEON XIII,110480.0,5466001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1082,2365,2022,MAYO,207.0,312770,1950-05-07,contributivo,1791.0,1950-05-07,ambulatorio,...,general,1950-05-07,unica via,44304,44304.0,G560,ortopedia,PRADO,132416.0,6121284
1083,2366,2022,MAYO,207.0,313334,1947-03-28,contributivo,1791.0,1947-03-28,ambulatorio,...,general,1947-03-28,unica via,44304,44304.0,G560,ortopedia,PRADO,132427.0,6121928
1084,2367,2022,JUNIO,213.0,307306,1936-10-15,contributivo,3289.0,1936-10-15,ambulatorio,...,local asistida,1936-10-15,multiple procedimiento mismo especialista dife...,867203,867203.0,C443,cirugia plastica,PRADO,132700.0,6129844
1085,2368,2022,JUNIO,203.0,307270,1956-12-22,contributivo,1791.0,1956-12-22,ambulatorio,...,general,1956-12-22,unica via,535204,535204.0,K439,cirugia general,PRADO,132904.0,6136389
1086,2369,2022,JUNIO,NaN,313523,1979-05-11,contributivo,1791.0,1979-05-11,ambulatorio,...,general,1979-05-11,unica via,862701,862701.0,L600,dermatologia,PRADO,133370.0,6150985

In [6]:
cronicos.head(5)

,Unnamed: 0,YEAR,MES,Fecha diligenciamiento,Hora,Atención,Ingreso,Tipo,NRODOC,Peso,...,VO2 - Máxima Cantidad de Oxígeno,Índice de Fragilidad Groningen,Calificación (Índice de Fragilidad),Tiempo en Segundos (Apoyo Monopodal),Calificación (Apoyo Monopodal),Tiempo en Segundos (Recorrer 5 metros),Velocidad (m/s),Calificación Velocidad,Requiere cita de morbilidad,Ambito según el médico
0,12827,2021,ENERO,2021-01-01,12:13:45 a.m.,5465666,3668418,CC,310176,56.0,...,13.8855,9.0,Frágil,9,Malo - Fragil,6,0.83,Deficiente,Si,Domiciliario
1,12828,2021,ENERO,2021-01-01,8:01:46 p.m.,5459773,3670506,CC,312214,39.0,...,35.3671,8.0,Frágil,10,Aceptable,6,0.83,Deficiente,Si,Domiciliario
2,12829,2021,ENERO,2021-01-03,8:41:16 p.m.,5456426,3670496,CC,311627,88.0,...,12.5212,9.0,Frágil,0,Malo - Fragil,0,0.00,Malo - Frágil,No,Domiciliario
3,12831,2021,ENERO,2021-01-04,8:33:34 a.m.,4306788,3669378,CC,307827,65.2,...,17.2497,10.0,Frágil,0,Malo - Fragil,9,0.56,Malo - Frágil,Si,Domiciliario
4,12833,2021,ENERO,2021-01-04,8:40:58 a.m.,5325410,3670145,CC,312431,55.0,...,13.0032,4.0,Normal,6,Malo - Fragil,8,0.63,Deficiente,No,Domiciliario

In [7]:
cronicos.columns.values

array(['Unnamed: 0', 'YEAR', 'MES', 'Fecha diligenciamiento', 'Hora',
       'Atención', 'Ingreso', 'Tipo', 'NRODOC', 'Peso', 'Talla', 'IMC',
       'Clasificación IMC', 'Saturación de Oxígeno (%)',
       'Perímetro Muslo', 'Perímetro Cintura', 'Pliegue Triceps',
       'Pliegue Abdomen', 'Pliegue Muslo', 'Sumatoria Pliegues',
       'Presión Arterial Sistólica', 'Presión Arterial Diastólica',
       'Frecuencia Cardíaca en reposo',
       'Auto-calificacion Nivel de Ejercicio', 'Constantes',
       'METS -Índice Metabólico', 'VO2 - Máxima Cantidad de Oxígeno',
       'Índice de Fragilidad Groningen',
       'Calificación (Índice de Fragilidad)',
       'Tiempo en Segundos (Apoyo Monopodal)',
       'Calificación (Apoyo Monopodal)',
       'Tiempo en Segundos (Recorrer 5 metros)', 'Velocidad (m/s)',
       'Calificación Velocidad', 'Requiere cita de morbilidad',
       'Ambito según el médico'], dtype=object)

In [20]:
cronicos = cronicos.drop(['Tipo','Clasificación IMC','Calificación (Índice de Fragilidad)','Calificación (Apoyo Monopodal)','Calificación Velocidad'], axis=1)
cronicos

,Unnamed: 0,YEAR,MES,Fecha diligenciamiento,Hora,Atención,Ingreso,NRODOC,Peso,Talla,...,Auto-calificacion Nivel de Ejercicio,Constantes,METS -Índice Metabólico,VO2 - Máxima Cantidad de Oxígeno,Índice de Fragilidad Groningen,Tiempo en Segundos (Apoyo Monopodal),Tiempo en Segundos (Recorrer 5 metros),Velocidad (m/s),Requiere cita de morbilidad,Ambito según el médico
0,12827,2021,ENERO,2021-01-01,12:13:45 a.m.,5465666,3668418,310176,56.0,155.0,...,1,0.00,3.9673,13.8855,9.0,9,6,0.83,Si,Domiciliario
1,12828,2021,ENERO,2021-01-01,8:01:46 p.m.,5459773,3670506,312214,39.0,156.0,...,1,0.00,10.1049,35.3671,8.0,10,6,0.83,Si,Domiciliario
2,12829,2021,ENERO,2021-01-03,8:41:16 p.m.,5456426,3670496,311627,88.0,158.0,...,1,0.00,3.5775,12.5212,9.0,0,0,0.00,No,Domiciliario
3,12831,2021,ENERO,2021-01-04,8:33:34 a.m.,4306788,3669378,307827,65.2,165.0,...,1,0.00,4.9285,17.2497,10.0,0,9,0.56,Si,Domiciliario
4,12833,2021,ENERO,2021-01-04,8:40:58 a.m.,5325410,3670145,312431,55.0,150.0,...,1,0.00,3.7152,13.0032,4.0,6,8,0.63,No,Domiciliario
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25284,38731,2022,MAYO,2022-05-31,10:55:31 p.m.,3419528,3630125,308916,65.0,165.0,...,1,0.00,4.3204,15.1214,8.0,0,9,0.56,No,Domiciliario
25285,38732,2022,MAYO,2022-05-31,10:59:58 p.m.,5850632,4314997,306248,60.0,160.0,...,1,0.00,3.9052,13.6682,7.0,2,9,0.56,No,Domiciliario
25286,38733,2022,MAYO,2022-05-31,11:13:57 p.m.,3413909,3630054,310546,48.0,160.0,...,1,0.00,4.3425,15.1988,9.0,0,0,0.00,No,Domiciliario
25287,38734,2022,MAYO,2022-05-31,11:17:35 p.m.,5783823,4089709,309601,60.0,165.0,...,3,1.06,4.9332,17.2662,9.0,0,0,0.00,No,Domiciliario
25288,38735,2022,MAYO,2022-05-31,11:25:39 p.m.,3991645,3434751,311850,75.0,164.0,...,1,0.00,3.5687,12.4904,8.0,1,6,0.83,No,Domiciliario

In [27]:
cronicos.columns= cronicos.columns.str.lower()
cx.columns= cx.columns.str.lower()

,unnamed: 0,year,mes,codigo servicio habilitacion,nrodoc,fecha nacimiento,regimen,codigo eps,fecha orden,origen orden,...,tipo de anestesia,fecha recuperacion cx,via,cod cups,procedimiento 0256,cod diagnostico prequirurgico,especialidad,sede,idcx,admision
0,854,2021,ENERO,207.0,308384,1971-02-10,subsidiado,1415.0,1971-02-10,urgencias adultos,...,ninguna,1971-02-10,unica via,862006,862006.0,T818,ortopedia,LEON XIII,109718.0,5466001
1,855,2021,ENERO,215.0,308384,1971-02-10,subsidiado,1415.0,1971-02-10,ambulatorio,...,NaN,1971-02-10,unica via,580050,580050.0,N359,urologia,LEON XIII,109856.0,5466001
2,856,2021,ENERO,207.0,308384,1971-02-10,subsidiado,1415.0,1971-02-10,ambulatorio,...,general,1971-02-10,multiple procedimiento mismo especialista igua...,770501,770501.0,M869,ortopedia,LEON XIII,110056.0,5466001
3,857,2021,ENERO,207.0,308384,1971-02-10,subsidiado,1415.0,1971-02-10,ambulatorio,...,local asistida,1971-02-10,multiple procedimiento mismo especialista igua...,770501,770501.0,M866,ortopedia,LEON XIII,110349.0,5466001
4,858,2021,ENERO,207.0,308384,1971-02-10,subsidiado,1415.0,1971-02-10,ambulatorio,...,NaN,1971-02-10,unica via,770501,770501.0,M864,ortopedia,LEON XIII,110480.0,5466001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1082,2365,2022,MAYO,207.0,312770,1950-05-07,contributivo,1791.0,1950-05-07,ambulatorio,...,general,1950-05-07,unica via,44304,44304.0,G560,ortopedia,PRADO,132416.0,6121284
1083,2366,2022,MAYO,207.0,313334,1947-03-28,contributivo,1791.0,1947-03-28,ambulatorio,...,general,1947-03-28,unica via,44304,44304.0,G560,ortopedia,PRADO,132427.0,6121928
1084,2367,2022,JUNIO,213.0,307306,1936-10-15,contributivo,3289.0,1936-10-15,ambulatorio,...,local asistida,1936-10-15,multiple procedimiento mismo especialista dife...,867203,867203.0,C443,cirugia plastica,PRADO,132700.0,6129844
1085,2368,2022,JUNIO,203.0,307270,1956-12-22,contributivo,1791.0,1956-12-22,ambulatorio,...,general,1956-12-22,unica via,535204,535204.0,K439,cirugia general,PRADO,132904.0,6136389
1086,2369,2022,JUNIO,NaN,313523,1979-05-11,contributivo,1791.0,1979-05-11,ambulatorio,...,general,1979-05-11,unica via,862701,862701.0,L600,dermatologia,PRADO,133370.0,6150985

In [22]:
usuarios

,Unnamed: 0,mes,año,nrodoc,sexo,edad,municipio,ciclo_vital,quinquenio
0,101490,enero,2021,311028,m,69,sabaneta,vejez,65-69
1,101491,enero,2021,310961,m,75,bello,vejez,75-79
2,101492,enero,2021,311235,f,85,medellin,vejez,85-89
3,101493,enero,2021,307090,f,88,medellin,vejez,85-89
4,101494,enero,2021,310309,f,79,medellin,vejez,75-79
...,...,...,...,...,...,...,...,...,...
82416,183906,junio,2022,307482,f,81,medellin,vejez,80-84
82417,183907,junio,2022,313801,f,23,sin información,juventud,20-24
82418,183908,junio,2022,307738,f,78,medellin,vejez,75-79
82419,183909,junio,2022,311656,m,82,medellin,vejez,80-84
82420,183910,junio,2022,309230,m,65,envigado,vejez,65-69

In [23]:
usuarios = usuarios.drop(['ciclo_vital','quinquenio'],axis=1)

In [33]:
cx

,unnamed: 0,year,mes,codigo servicio habilitacion,nrodoc,fecha nacimiento,regimen,codigo eps,fecha orden,origen orden,...,tipo de anestesia,fecha recuperacion cx,via,cod cups,procedimiento 0256,cod diagnostico prequirurgico,especialidad,sede,idcx,admision
0,854,2021,ENERO,207.0,308384,1971-02-10,subsidiado,1415.0,1971-02-10,urgencias adultos,...,ninguna,1971-02-10,unica via,862006,862006.0,T818,ortopedia,LEON XIII,109718.0,5466001
1,855,2021,ENERO,215.0,308384,1971-02-10,subsidiado,1415.0,1971-02-10,ambulatorio,...,NaN,1971-02-10,unica via,580050,580050.0,N359,urologia,LEON XIII,109856.0,5466001
2,856,2021,ENERO,207.0,308384,1971-02-10,subsidiado,1415.0,1971-02-10,ambulatorio,...,general,1971-02-10,multiple procedimiento mismo especialista igua...,770501,770501.0,M869,ortopedia,LEON XIII,110056.0,5466001
3,857,2021,ENERO,207.0,308384,1971-02-10,subsidiado,1415.0,1971-02-10,ambulatorio,...,local asistida,1971-02-10,multiple procedimiento mismo especialista igua...,770501,770501.0,M866,ortopedia,LEON XIII,110349.0,5466001
4,858,2021,ENERO,207.0,308384,1971-02-10,subsidiado,1415.0,1971-02-10,ambulatorio,...,NaN,1971-02-10,unica via,770501,770501.0,M864,ortopedia,LEON XIII,110480.0,5466001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1082,2365,2022,MAYO,207.0,312770,1950-05-07,contributivo,1791.0,1950-05-07,ambulatorio,...,general,1950-05-07,unica via,44304,44304.0,G560,ortopedia,PRADO,132416.0,6121284
1083,2366,2022,MAYO,207.0,313334,1947-03-28,contributivo,1791.0,1947-03-28,ambulatorio,...,general,1947-03-28,unica via,44304,44304.0,G560,ortopedia,PRADO,132427.0,6121928
1084,2367,2022,JUNIO,213.0,307306,1936-10-15,contributivo,3289.0,1936-10-15,ambulatorio,...,local asistida,1936-10-15,multiple procedimiento mismo especialista dife...,867203,867203.0,C443,cirugia plastica,PRADO,132700.0,6129844
1085,2368,2022,JUNIO,203.0,307270,1956-12-22,contributivo,1791.0,1956-12-22,ambulatorio,...,general,1956-12-22,unica via,535204,535204.0,K439,cirugia general,PRADO,132904.0,6136389
1086,2369,2022,JUNIO,NaN,313523,1979-05-11,contributivo,1791.0,1979-05-11,ambulatorio,...,general,1979-05-11,unica via,862701,862701.0,L600,dermatologia,PRADO,133370.0,6150985

In [28]:
cx.columns

Index(['unnamed: 0', 'year', 'mes', 'codigo servicio habilitacion', 'nrodoc',
       'fecha nacimiento', 'regimen', 'codigo eps', 'fecha orden',
       'origen orden', 'origen admsion', 'quirofano', 'tipo procedimiento',
       'fecha preanestesia', 'fecha cirugia', 'tipo de anestesia',
       'fecha recuperacion cx', 'via', 'cod cups', 'procedimiento 0256',
       'cod diagnostico prequirurgico', 'especialidad', 'sede', 'idcx',
       'admision'],
      dtype='object')

In [49]:
cx.columns= cx.columns.str.lower()

In [51]:
#Aplicar funciones para homologar a nivel general.
lista = ['mes','sede']
for i in lista:
    cx[i] = cx[i].str.lower() #minuscula
    cx[i] = cx[i].str.strip() #espacios
    cx[i] = cx[i].apply(lambda x: normalize("NFKD", x).encode("ascii", "ignore").decode("ascii") if pd.notnull(x) else x)

In [52]:
cx1 = cx.groupby(['nrodoc'])[['unnamed: 0']].count().reset_index()
cx1.rename(columns = {'unnamed: 0':'cantidad de cirugias'},inplace=True)
cx1

     nrodoc  cantidad de cirugias
0    306221                     1
1    306230                     3
2    306233                     1
3    306259                     1
4    306271                     1
..      ...                   ...
723  314120                     1
724  314125                     1
725  314172                     1
726  314182                     1
727  314187                     1

[728 rows x 2 columns]

In [61]:
dfcx = pd.merge(cx1,cx, on = 'nrodoc',how = 'inner')
dfcx

,nrodoc,cantidad de cirugias,unnamed: 0,year,mes,codigo servicio habilitacion,fecha nacimiento,regimen,codigo eps,fecha orden,...,tipo de anestesia,fecha recuperacion cx,via,cod cups,procedimiento 0256,cod diagnostico prequirurgico,especialidad,sede,idcx,admision
0,306221,1,1532,2022,enero,217.0,1938-09-09,contributivo,1415.0,1938-09-09,...,local,1938-09-09,unica via,53113,53113.0,M170,medicina del dolor y cuidado paliativo,leon xiii,126470.0,5919903
1,306230,3,1486,2021,diciembre,203.0,1940-01-25,subsidiado,1415.0,1940-01-25,...,general,1940-01-25,multiple procedimiento mismo especialista igua...,517301,517301.0,K650,otras cirugias,leon xiii,125132.0,5929611
2,306230,3,1487,2021,diciembre,203.0,1940-01-25,subsidiado,1415.0,1940-01-25,...,general,1940-01-25,multiple procedimiento mismo especialista igua...,512101,512101.0,K650,cirugia general,leon xiii,125132.0,5929611
3,306230,3,1495,2022,enero,245.0,1940-01-25,contributivo,1415.0,1940-01-25,...,general,1940-01-25,unica via,24300,24300.0,G919,neurocirugia,leon xiii,125361.0,5929611
4,306233,1,1801,2022,mayo,207.0,1942-07-22,contributivo,2889.0,1942-07-22,...,raquidea,1942-07-22,unica via,793501,793501.0,S721,ortopedia,leon xiii,132024.0,6105562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1082,314120,1,1593,2022,febrero,207.0,1962-04-22,contributivo,1415.0,1962-04-22,...,general,1962-04-22,multiple procedimiento mismo especialista igua...,780300,780300.0,S525,ortopedia,leon xiii,127707.0,5992455
1083,314125,1,1803,2022,mayo,213.0,1948-09-10,contributivo,2889.0,1948-09-10,...,general,1948-09-10,multiple procedimiento mismo especialista igua...,867203,867203.0,C443,cirugia plastica,leon xiii,132106.0,6080691
1084,314172,1,1685,2022,marzo,214.0,1938-01-01,contributivo,1415.0,1938-01-01,...,epidural,1938-01-01,unica via,841700,841700.0,I702,cirugia vascular,leon xiii,129503.0,6035935
1085,314182,1,1610,2022,marzo,207.0,1926-12-05,contributivo,2889.0,1926-12-05,...,raquidea,1926-12-05,unica via,793501,793501.0,S721,ortopedia,leon xiii,128140.0,6003330
1086,314187,1,1562,2022,febrero,214.0,1942-07-27,contributivo,2891.0,1942-07-27,...,general,1942-07-27,unica via,841700,841700.0,I771,cirugia vascular,leon xiii,127105.0,5976438

In [37]:
cx[cx['nrodoc']==314187]

,unnamed: 0,year,mes,codigo servicio habilitacion,nrodoc,fecha nacimiento,regimen,codigo eps,fecha orden,origen orden,...,tipo de anestesia,fecha recuperacion cx,via,cod cups,procedimiento 0256,cod diagnostico prequirurgico,especialidad,sede,idcx,admision
708,1562,2022,FEBRERO,214.0,314187,1942-07-27,contributivo,2891.0,1942-07-27,ambulatorio,...,general,1942-07-27,unica via,841700,841700.0,I771,cirugia vascular,LEON XIII,127105.0,5976438

In [54]:
dfcx=dfcx.drop_duplicates()

In [55]:
dfcx.isnull().sum()

nrodoc                             0
cantidad de cirugias               0
unnamed: 0                         0
year                               0
mes                                0
codigo servicio habilitacion       6
fecha nacimiento                   0
regimen                            0
codigo eps                         0
fecha orden                        0
origen orden                       0
origen admsion                     0
quirofano                          0
tipo procedimiento                 0
fecha preanestesia                 0
fecha cirugia                      0
tipo de anestesia                151
fecha recuperacion cx              0
via                                0
cod cups                           0
procedimiento 0256                 0
cod diagnostico prequirurgico      0
especialidad                       0
sede                               0
idcx                               0
admision                           0
dtype: int64

In [60]:
dfcx

,nrodoc,cantidad de cirugias,unnamed: 0,year,mes,codigo servicio habilitacion,fecha nacimiento,regimen,codigo eps,fecha orden,...,tipo de anestesia,fecha recuperacion cx,via,cod cups,procedimiento 0256,cod diagnostico prequirurgico,especialidad,sede,idcx,admision
0,306221,1,1532,2022,enero,217.0,1938-09-09,contributivo,1415.0,1938-09-09,...,local,1938-09-09,unica via,53113,53113.0,M170,medicina del dolor y cuidado paliativo,leon xiii,126470.0,5919903
1,306230,3,1486,2021,diciembre,203.0,1940-01-25,subsidiado,1415.0,1940-01-25,...,general,1940-01-25,multiple procedimiento mismo especialista igua...,517301,517301.0,K650,otras cirugias,leon xiii,125132.0,5929611
2,306230,3,1487,2021,diciembre,203.0,1940-01-25,subsidiado,1415.0,1940-01-25,...,general,1940-01-25,multiple procedimiento mismo especialista igua...,512101,512101.0,K650,cirugia general,leon xiii,125132.0,5929611
3,306230,3,1495,2022,enero,245.0,1940-01-25,contributivo,1415.0,1940-01-25,...,general,1940-01-25,unica via,24300,24300.0,G919,neurocirugia,leon xiii,125361.0,5929611
4,306233,1,1801,2022,mayo,207.0,1942-07-22,contributivo,2889.0,1942-07-22,...,raquidea,1942-07-22,unica via,793501,793501.0,S721,ortopedia,leon xiii,132024.0,6105562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1082,314120,1,1593,2022,febrero,207.0,1962-04-22,contributivo,1415.0,1962-04-22,...,general,1962-04-22,multiple procedimiento mismo especialista igua...,780300,780300.0,S525,ortopedia,leon xiii,127707.0,5992455
1083,314125,1,1803,2022,mayo,213.0,1948-09-10,contributivo,2889.0,1948-09-10,...,general,1948-09-10,multiple procedimiento mismo especialista igua...,867203,867203.0,C443,cirugia plastica,leon xiii,132106.0,6080691
1084,314172,1,1685,2022,marzo,214.0,1938-01-01,contributivo,1415.0,1938-01-01,...,epidural,1938-01-01,unica via,841700,841700.0,I702,cirugia vascular,leon xiii,129503.0,6035935
1085,314182,1,1610,2022,marzo,207.0,1926-12-05,contributivo,2889.0,1926-12-05,...,raquidea,1926-12-05,unica via,793501,793501.0,S721,ortopedia,leon xiii,128140.0,6003330
1086,314187,1,1562,2022,febrero,214.0,1942-07-27,contributivo,2891.0,1942-07-27,...,general,1942-07-27,unica via,841700,841700.0,I771,cirugia vascular,leon xiii,127105.0,5976438